// This file is auto-generated by rpc.compiler

using System;
using Acoross.Network.Rpc.Sync;

namespace Acoross.tw.Rpc
{
    interface RpcSync
    {
        bool Login(LoginReq req);
        bool Dash(DashReq req);
    }

    interface NotiSync
    {
        void NotiPosSync(vec2 message);
        void NotiDashEnd(vec2 message);
        void BroadcastDash(DashBroadcast message);
    }

    abstract class RpcClientSync : RpcClientSyncBase, RpcSync, NotiSync
    {
        protected RpcClientSync()
        {
            TryRegisterNoti<vec2>((int)NotiTypes.NotiPosSync, NotiPosSync);
            TryRegisterNoti<vec2>((int)NotiTypes.NotiDashEnd, NotiDashEnd);
            TryRegisterNoti<DashBroadcast>((int)NotiTypes.BroadcastDash, BroadcastDash);
        }

        public bool Login(LoginReq req)
        {
            return CallRemoteProcedure<LoginReq, bool>((int)RpcTypes.Login, req);
        }

        public bool Dash(DashReq req)
        {
            return CallRemoteProcedure<DashReq, bool>((int)RpcTypes.Dash, req);
        }

        public abstract void NotiPosSync(vec2 message);
        public abstract void NotiDashEnd(vec2 message);
        public abstract void BroadcastDash(DashBroadcast message);
    }
}
