// This file is auto-generated by rpc.compiler

using System;
using System.Threading.Tasks;
using Acoross.Network.Rpc;

namespace Acoross.tw.Rpc
{
    interface Rpc
    {
        Task<bool> Login(LoginReq req);
        Task<bool> Dash(DashReq req);
    }

    interface Noti
    {
        Task NotiPosSync(vec2 message);
        Task NotiDashEnd(vec2 message);
    }

    abstract class RpcClient : RpcClientBase, Rpc, Noti
    {
        protected RpcClient()
        {
            TryRegisterNoti<vec2>((int)NotiTypes.NotiPosSync, NotiPosSync);
            TryRegisterNoti<vec2>((int)NotiTypes.NotiDashEnd, NotiDashEnd);
        }

        public async Task<bool> Login(LoginReq req)
        {
            return await CallRemoteProcedure<LoginReq, bool>((int)RpcTypes.Login, req);
        }

        public async Task<bool> Dash(DashReq req)
        {
            return await CallRemoteProcedure<DashReq, bool>((int)RpcTypes.Dash, req);
        }

        public abstract Task NotiPosSync(vec2 message);
        public abstract Task NotiDashEnd(vec2 message);
    }
}
