// This file is auto-generated by rpc.compiler

using System;
using System.Net.Sockets;
using System.Threading.Tasks;
using Acoross.Network.Rpc;

namespace Acoross.tw.Rpc
{
    interface Rpc
    {
        Task<bool> Login(LoginReq req);
        Task<bool> Dash(DashReq req);
    }

    interface Noti
    {
        Task NotiPosSync(vec2 message);
        Task NotiDashEnd(vec2 message);
        Task BroadcastDash(DashBroadcast message);
    }

    abstract class RpcSession : RpcSessionBase, Rpc, Noti
    {
        public RpcSession(Socket systemsocket) : base(systemsocket)
        {
            TryRegister<LoginReq, bool>((int)RpcTypes.Login, Login);
            TryRegister<DashReq, bool>((int)RpcTypes.Dash, Dash);
        }

        public abstract Task<bool> Login(LoginReq req);
        public abstract Task<bool> Dash(DashReq req);

        public Task NotiPosSync(vec2 message)
        {
            return Noti((int)NotiTypes.NotiPosSync, message);
        }

        public Task NotiDashEnd(vec2 message)
        {
            return Noti((int)NotiTypes.NotiDashEnd, message);
        }

        public Task BroadcastDash(DashBroadcast message)
        {
            return Noti((int)NotiTypes.BroadcastDash, message);
        }
    }
}
